// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item_repository.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockUserRequest) Reset()         { *m = BlockUserRequest{} }
func (m *BlockUserRequest) String() string { return proto.CompactTextString(m) }
func (*BlockUserRequest) ProtoMessage()    {}
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_repository_a96c5046ef22d7f6, []int{0}
}
func (m *BlockUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockUserRequest.Unmarshal(m, b)
}
func (m *BlockUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockUserRequest.Marshal(b, m, deterministic)
}
func (dst *BlockUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockUserRequest.Merge(dst, src)
}
func (m *BlockUserRequest) XXX_Size() int {
	return xxx_messageInfo_BlockUserRequest.Size(m)
}
func (m *BlockUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockUserRequest proto.InternalMessageInfo

func (m *BlockUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BlockUserResponse struct {
	Rez                  bool     `protobuf:"varint,1,opt,name=rez,proto3" json:"rez,omitempty"`
	Errname              string   `protobuf:"bytes,2,opt,name=errname,proto3" json:"errname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockUserResponse) Reset()         { *m = BlockUserResponse{} }
func (m *BlockUserResponse) String() string { return proto.CompactTextString(m) }
func (*BlockUserResponse) ProtoMessage()    {}
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_repository_a96c5046ef22d7f6, []int{1}
}
func (m *BlockUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockUserResponse.Unmarshal(m, b)
}
func (m *BlockUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockUserResponse.Marshal(b, m, deterministic)
}
func (dst *BlockUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockUserResponse.Merge(dst, src)
}
func (m *BlockUserResponse) XXX_Size() int {
	return xxx_messageInfo_BlockUserResponse.Size(m)
}
func (m *BlockUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockUserResponse proto.InternalMessageInfo

func (m *BlockUserResponse) GetRez() bool {
	if m != nil {
		return m.Rez
	}
	return false
}

func (m *BlockUserResponse) GetErrname() string {
	if m != nil {
		return m.Errname
	}
	return ""
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_repository_a96c5046ef22d7f6, []int{2}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemRequest) Reset()         { *m = CreateItemRequest{} }
func (m *CreateItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateItemRequest) ProtoMessage()    {}
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_repository_a96c5046ef22d7f6, []int{3}
}
func (m *CreateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemRequest.Unmarshal(m, b)
}
func (m *CreateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemRequest.Marshal(b, m, deterministic)
}
func (dst *CreateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemRequest.Merge(dst, src)
}
func (m *CreateItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateItemRequest.Size(m)
}
func (m *CreateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemRequest proto.InternalMessageInfo

func (m *CreateItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateItemRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ListItemResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemResponse) Reset()         { *m = ListItemResponse{} }
func (m *ListItemResponse) String() string { return proto.CompactTextString(m) }
func (*ListItemResponse) ProtoMessage()    {}
func (*ListItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_repository_a96c5046ef22d7f6, []int{4}
}
func (m *ListItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemResponse.Unmarshal(m, b)
}
func (m *ListItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemResponse.Marshal(b, m, deterministic)
}
func (dst *ListItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemResponse.Merge(dst, src)
}
func (m *ListItemResponse) XXX_Size() int {
	return xxx_messageInfo_ListItemResponse.Size(m)
}
func (m *ListItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemResponse proto.InternalMessageInfo

func (m *ListItemResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListItemsRequest struct {
	PriceRight           int64    `protobuf:"varint,1,opt,name=price_right,json=priceRight,proto3" json:"price_right,omitempty"`
	PriceLeft            int64    `protobuf:"varint,2,opt,name=price_left,json=priceLeft,proto3" json:"price_left,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemsRequest) Reset()         { *m = ListItemsRequest{} }
func (m *ListItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ListItemsRequest) ProtoMessage()    {}
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_repository_a96c5046ef22d7f6, []int{5}
}
func (m *ListItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemsRequest.Unmarshal(m, b)
}
func (m *ListItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemsRequest.Marshal(b, m, deterministic)
}
func (dst *ListItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemsRequest.Merge(dst, src)
}
func (m *ListItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ListItemsRequest.Size(m)
}
func (m *ListItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemsRequest proto.InternalMessageInfo

func (m *ListItemsRequest) GetPriceRight() int64 {
	if m != nil {
		return m.PriceRight
	}
	return 0
}

func (m *ListItemsRequest) GetPriceLeft() int64 {
	if m != nil {
		return m.PriceLeft
	}
	return 0
}

func (m *ListItemsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListItemsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockUserRequest)(nil), "proto.BlockUserRequest")
	proto.RegisterType((*BlockUserResponse)(nil), "proto.BlockUserResponse")
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*CreateItemRequest)(nil), "proto.CreateItemRequest")
	proto.RegisterType((*ListItemResponse)(nil), "proto.ListItemResponse")
	proto.RegisterType((*ListItemsRequest)(nil), "proto.ListItemsRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemRepositoryClient is the client API for ItemRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemRepositoryClient interface {
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*Item, error)
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*Item, error)
	BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*BlockUserResponse, error)
}

type itemRepositoryClient struct {
	cc *grpc.ClientConn
}

func NewItemRepositoryClient(cc *grpc.ClientConn) ItemRepositoryClient {
	return &itemRepositoryClient{cc}
}

func (c *itemRepositoryClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/proto.ItemRepository/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemRepositoryClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/proto.ItemRepository/ListItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemRepositoryClient) BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*BlockUserResponse, error) {
	out := new(BlockUserResponse)
	err := c.cc.Invoke(ctx, "/proto.ItemRepository/BlockUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemRepositoryServer is the server API for ItemRepository service.
type ItemRepositoryServer interface {
	CreateItem(context.Context, *CreateItemRequest) (*Item, error)
	ListItems(context.Context, *ListItemsRequest) (*Item, error)
	BlockUser(context.Context, *BlockUserRequest) (*BlockUserResponse, error)

}

func RegisterItemRepositoryServer(s *grpc.Server, srv ItemRepositoryServer) {
	s.RegisterService(&_ItemRepository_serviceDesc, srv)
}

func _ItemRepository_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemRepositoryServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemRepository/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemRepositoryServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemRepository_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemRepositoryServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemRepository/ListItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemRepositoryServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemRepository_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemRepositoryServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemRepository/BlockUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemRepositoryServer).BlockUser(ctx, req.(*BlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemRepository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ItemRepository",
	HandlerType: (*ItemRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _ItemRepository_CreateItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _ItemRepository_ListItems_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _ItemRepository_BlockUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_repository.proto",
}

func init() {
	proto.RegisterFile("item_repository.proto", fileDescriptor_item_repository_a96c5046ef22d7f6)
}

var fileDescriptor_item_repository_a96c5046ef22d7f6 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x6f, 0xf2, 0x30,
	0x10, 0xc6, 0x71, 0x42, 0x78, 0xdf, 0x1c, 0x12, 0x02, 0xab, 0x7f, 0x2c, 0xa4, 0xaa, 0xa9, 0xa7,
	0x4c, 0x0c, 0x20, 0xba, 0x55, 0x45, 0xed, 0x54, 0x89, 0xc9, 0x52, 0x67, 0x44, 0xe1, 0xd2, 0x5a,
	0x25, 0x38, 0xb5, 0xdd, 0xa1, 0x9d, 0xfa, 0xc9, 0xfa, 0xd9, 0xaa, 0xd8, 0x09, 0x44, 0xd0, 0xa1,
	0x13, 0xbe, 0x3b, 0x7e, 0xbe, 0xe7, 0x79, 0x1c, 0x38, 0x95, 0x16, 0xf3, 0x85, 0xc6, 0x42, 0x19,
	0x69, 0x95, 0xfe, 0x18, 0x15, 0x5a, 0x59, 0x45, 0x23, 0xf7, 0xc3, 0xaf, 0xa1, 0x7f, 0xb7, 0x51,
	0xab, 0xd7, 0x47, 0x83, 0x5a, 0xe0, 0xdb, 0x3b, 0x1a, 0x4b, 0x7b, 0x10, 0xc8, 0x35, 0x23, 0x09,
	0x49, 0x23, 0x11, 0xc8, 0x35, 0xa5, 0xd0, 0xde, 0x2e, 0x73, 0x64, 0x41, 0x42, 0xd2, 0x58, 0xb8,
	0x33, 0xbf, 0x85, 0x41, 0x83, 0x33, 0x85, 0xda, 0x1a, 0xa4, 0x7d, 0x08, 0x35, 0x7e, 0x3a, 0xf2,
	0xbf, 0x28, 0x8f, 0x94, 0xc1, 0x3f, 0xd4, 0xba, 0x41, 0xd7, 0x25, 0x9f, 0x41, 0xfb, 0xc1, 0x62,
	0xfe, 0x97, 0x65, 0xf4, 0x04, 0xa2, 0x42, 0xcb, 0x15, 0xb2, 0x30, 0x21, 0x69, 0x28, 0x7c, 0xc1,
	0x6f, 0x60, 0x70, 0xaf, 0x71, 0x69, 0xb1, 0xbc, 0xa7, 0xd6, 0x5e, 0xe3, 0xe4, 0x37, 0x3c, 0x68,
	0xe2, 0x53, 0xe8, 0xcf, 0xa5, 0xb1, 0x1e, 0xae, 0x0c, 0x5c, 0x41, 0x54, 0xa6, 0x65, 0x18, 0x49,
	0xc2, 0xb4, 0x3b, 0xee, 0xfa, 0xac, 0x46, 0xee, 0x3f, 0x7e, 0xc2, 0xbf, 0xc8, 0x9e, 0x33, 0xf5,
	0xd6, 0x4b, 0xe8, 0xba, 0x4b, 0x17, 0x5a, 0x3e, 0xbf, 0x58, 0xb7, 0x3c, 0x14, 0xe0, 0x5a, 0xa2,
	0xec, 0xd0, 0x0b, 0xf0, 0xd5, 0x62, 0x83, 0x99, 0xad, 0x74, 0xc4, 0xae, 0x33, 0xc7, 0xcc, 0x96,
	0x0a, 0x37, 0x32, 0x97, 0xd6, 0x19, 0x8c, 0x84, 0x2f, 0xe8, 0x19, 0x74, 0x54, 0x96, 0x19, 0xb4,
	0xac, 0xed, 0xda, 0x55, 0x35, 0xfe, 0x26, 0xd0, 0xf3, 0xb2, 0xeb, 0x37, 0xa5, 0x53, 0x80, 0x7d,
	0x16, 0x94, 0x55, 0xba, 0x8f, 0xe2, 0x19, 0x36, 0x1d, 0xf1, 0x16, 0x9d, 0x40, 0xbc, 0xf3, 0x42,
	0xcf, 0xab, 0xd9, 0xa1, 0xbb, 0x43, 0x68, 0x06, 0xf1, 0xee, 0xe9, 0x77, 0xd0, 0xe1, 0x47, 0x34,
	0x64, 0xc7, 0x03, 0x1f, 0x32, 0x6f, 0x3d, 0x75, 0xdc, 0x68, 0xf2, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x39, 0x93, 0x5f, 0xde, 0x9b, 0x02, 0x00, 0x00,
}
